### ISSUE TITLE
please release apk?

### ISSUE THREAD

**Issue by g4269159** [daose/KissAnime#1]
I don't really know about programming and stuff, but I'd like to use this app...

**Comment by daose** [comment]
I'll try and get an early release out by the end of this week! If you could test it and tell me about anything to improve/bugs it'd be greatly appreciated.

**Comment by g4269159** [comment]
Thank you very much! And yes, sure!

**Comment by daose** [comment]
released

**Comment by g4269159** [comment]
Tried on xiaomi redmi 2, watched latest ep of Naruto Shippuden. I think it would be good to make the default episode resolution lower, there was a lot of buffering after a few minutes into the episode even while using my home WiFi. I'm not too sure about the tabs, there's two tabs with popular anime and none with just updated anime.
